/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yun_software_yunlearn_jni_MyJni */

#ifndef _Included_com_yun_software_yunlearn_jni_MyJni
#define _Included_com_yun_software_yunlearn_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yun_software_yunlearn_jni_MyJni
 * Method:    testAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yun_software_yunlearn_jni_MyJni_testAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_yun_software_yunlearn_jni_MyJni
 * Method:    getHelloWord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yun_software_yunlearn_jni_MyJni_getHelloWord
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
